### ISSUE TITLE
the new v3 is giving error 

### ISSUE THREAD

**Issue by karimzaki** [CompliantSec/M365SAT#23]
Get-M365SATReport : A parameter cannot be found that matches parameter name 'CISV3'.

**Comment by asterictnl-lvdw** [comment]
Good morning @karimzaki ,

Please give me steps so I can reproduce it, and a screenshot regarding the issue. Then I can look into the code where the issue might be caused. Please give me the full command what you are trying to execute as well.

Have you tried to execute the M365SATTester.ps1 to see if that is working?

Also the Parameter is called 'AuditType' and has the value CISV2 or CISV3. Keep that in mind.

Kind regards,

~LvdW

Update 08:51: I saw I made a mistake in the M365SATTester.ps1 I will fix this now for you. Then you can execute it once again.

**Comment by karimzaki** [comment]
i m running 
.\M365SATTester.ps1 i think you forgot to add audit type and also CISv3 parameter reference

**Comment by asterictnl-lvdw** [comment]
Yeah I think I have made a mix-up with the parameter. I will push the right M365SATTester.ps1 for you. 

You can replace ```-CISV3``` with ```-AuditType "CISV3" ```

**Comment by karimzaki** [comment]
yes i changed this -AllowLogging "Warning" -UseCustomModules -AuditType CISV3

**Comment by asterictnl-lvdw** [comment]
That works right? Because then I will push it to production asap.

Thanks in advance.

~LvdW

**Comment by karimzaki** [comment]
working fine but i have comments. 
1- the Title of the HTML is V2.0 i think it shall be 3 
2- the sections have been changed in V3 Ex first section is Microsoft 365 admin center, Microsoft 365 Defender, Microsoft Purview, Microsoft Intune admin center and so on

**Comment by asterictnl-lvdw** [comment]
@karimzaki ,

Thank you for your input. To make sure I will look at the implementation please create a different issue for the 2nd one.  

The title of the HTML corresponds to the version of M365SAT and not the CIS Benchmark, this should be v2.1 in this case, but since there will be a release v2.1.1 with some minor fixes I will schedule it for the next release. 

Keep that in mind. For the other one, please make a different issue and describe as detailed as possible what you would like to see back. I will need to make a subcategory for that and I will put it on the TO-DO list for the next release, because that takes a bit more work than usual. I have now based the commands on their cmdlet so your suggestion a very good one. I will have to make an enhancement for that.

Thanks in advance.

~LvdW

**Comment by karimzaki** [comment]
ok thanks so much for that a script i really use it lot for clients
