### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by ThoughtContagion** [CompliantSec/M365SAT#3]
Noticed when running the tool that errors are presented on screen and reference the `Write-ErrorLog.ps1` file.

![image](https://user-images.githubusercontent.com/88730003/218839918-7dbee6ba-db08-463a-9a2e-b58e797398c1.png)

The `Write-ErrorLog.ps1` file is in your root directory, but the `executeinspectors.ps1` file uses `$Script:PSScriptRoot` to define the file path.
This can be solved by moving or copying the file from your root directory to the `M365SAT\core\executeinspectors` directory.

**Comment by asterictnl-lvdw** [comment]
Hey,

Thank you for reporting this bug. I will change it in the code for the next release so the Write-ErrorLog.ps1 will be in the core folder. This requires changes in both the Inspector files and some of the core modules and the main script.

As I said this is a beta version. Reporting the bugs do help me a lot improving the program. 

If you have any features that you want to see in the report or in the program itself, please do open another request :D

~ LvdW

**Comment by asterictnl-lvdw** [comment]
> Noticed when running the tool that errors are presented on screen and reference the `Write-ErrorLog.ps1` file.
> 
> ![image](https://user-images.githubusercontent.com/88730003/218839918-7dbee6ba-db08-463a-9a2e-b58e797398c1.png)
> 
> The `Write-ErrorLog.ps1` file is in your root directory, but the `executeinspectors.ps1` file uses `$Script:PSScriptRoot` to define the file path. This can be solved by moving or copying the file from your root directory to the `M365SAT\core\executeinspectors` directory.

Hi @ThoughtContagion , Instead of using the Write-ErrorLog I will be using PoShLog for now on. It supports better logging strategies. I have tested it and it seems to work flawlessly. It saves me adding the same code over and over again as well as I only create a Logger and Close the logger after the program closes, eventually when the program crashes I could add a way to close the logger so no unsafe release of logging will apply. 

In the next version of M365SAT I will add PoShLog to the code so it will be updated and installed as well. 

~ Leonardo

**Comment by asterictnl-lvdw** [comment]
@ThoughtContagion 

I have released the v2.0rc to be tested. Please consult the CHANGELOG.md for more information. 

Also in order to make the error-logging work. Please use the PoShLog module.

I will hereby close this issue as it has been resolved for now. If there are other issues, feel free to open another bugreport.

~Leonardo

**Comment by asterictnl-lvdw** [comment]
@ThoughtContagion ,

Let me know if you need some additional features at 365Inspect. Then I might be able to see if I can get some code for you. :)

~LvdW
