### ISSUE TITLE
Microsoft Graph needs to authenticate twice [BUG]

### ISSUE THREAD

**Issue by frisotrip** [CompliantSec/M365SAT#52]
Hello

There is a strange thing going on. When i run M365SATTester.ps1 it looks like the Graph module doesn't run completely.
The second time i run the script everything is going ok, and i get an popup as seen in the attachment.

Am i doing something wrong?
![2024-09-02 14_41_15-Windows 11 M365 Security check - VMware Workstation](https://github.com/user-attachments/assets/a4482228-3414-4870-945c-e66a868c9381)

**Comment by asterictnl-lvdw** [comment]
Hello,

I need to look further into this. Since this does not break anything it is considered, this might be because of an issue with the validation which is not done correctly and resulting into another authentication of Microsoft Graph.

I will let you know what causes this issue and if there is a fix available.

For now as a workaround just authenticate twice and accept the permissions given (if you want on behalf of the organization), unless stated otherwise from the organization itself.

~LvdW

**Comment by asterictnl-lvdw** [comment]
Okay, this has been fixed in the latest Alpha release. This is due to Azure's new V2 mechanism. I have disabled it during the audit because it conflicts with some inspectors and will be enabled when the audit is done.

I have tested this, and it seems to be working.

Closed.

~LvdW
