### ISSUE TITLE
Different results at different settings

### ISSUE THREAD

**Issue by frisotrip** [CompliantSec/M365SAT#54]
Hello

Most of the tenants i administer are useng M365 Business premium. When i change the -Module settings from "All" to -Modules Exchange,Azure,Office365,Sharepoint,Teams
Exchange and the other modules are giving me different results. I thought they should be the same.
Am i thinking wrong, and what is the best setting for that subscription.

**Comment by asterictnl-lvdw** [comment]
Please provide both commands so I can compare as well that you are using and getting different results with. Please also look at the Code of Conduct before submitting your issue next time to provide more context: https://github.com/asterictnl-lvdw/M365SAT/blob/production/CODE_OF_CONDUCT.md#report-bugs-using-githubs-issues

Your submissions contain very little to no context requiring me to ask additional information which should be present when the issue is reported.

Thank you.

~LvdW

**Comment by frisotrip** [comment]
Hmm

I tested it again, it looks like now it is the same when I have -Module All.
I will test it a couple of times at different environments and will come back to it

Friso

**Comment by asterictnl-lvdw** [comment]
Hi @frisotrip ,

Thank you for testing it out. Kindly let me know if you are having issues. I have updated the alpha version which has some better reporting capabilities when only reporting specific parts so not all drop-down menu's are given and the report is more compact as a result.

~LvdW
